### ISSUE TITLE
Cached query returns null for newly inserted data

### ISSUE THREAD

**Issue by aarjan** [readysettech/readyset#39]
I connected my node api to the readyset docker service. 
A user fetching query was cached in readyset. 
But on creating new user, i do not get the new user data from the api. 
I could see the new inserted row in both mysql db and in the readyset service through mysql shell.

This is the config for readyset in the docker-compose file which is working in swarm mode:
```
  readyset:
    image: public.ecr.aws/readyset/readyset:latest
    ports:
      - 5433:5433
      - 3307:3307
    depends_on:
      - mysql
    env_file: .env
    networks:
      - backend
    volumes:
      - ./readyset:/state
    environment:
      STANDALONE: "1"
      DB_DIR: "/state"
      DATABASE_TYPE: mysql
      QUERY_CACHING: explicit
      DEPLOYMENT: "quickstart_docker"
      UPSTREAM_DB_URL: mysql://root:root@mysql:3306/testdb
      LISTEN_ADDRESS: "0.0.0.0:5433"
    logging:
      <<: *logging
```
This is the readyset_docker logs when i fire the api request
```

nf_readyset.1.msuofpokgq43@ip-172-31-27-196    | 2023-02-15T15:36:14.933119Z  INFO readyset: Accepted new connection context=LogContext({"deployment": "quickstart_docker"})
nf_readyset.1.msuofpokgq43@ip-172-31-27-196    | 2023-02-15T15:36:14.933265Z  INFO Connecting to MySQL upstream{host=mysql port=3306 user=root}: readyset_mysql::upstream: Establishing connection context=LogContext({"deployment": "quickstart_docker"})
nf_readyset.1.msuofpokgq43@ip-172-31-27-196    | 2023-02-15T15:36:14.939268Z  INFO Connecting to MySQL upstream{host=mysql port=3306 user=root}: readyset_mysql::upstream: Established connection to upstream context=LogContext({"deployment": "quickstart_docker"})
```
